spring:
  application:
    name: schema-auto-migration-cassandra-sample
  cassandra:
    contact-points: ${CASSANDRA_CONTACT_POINTS:localhost}
    port: ${CASSANDRA_PORT:9042}
    local-datacenter: ${CASSANDRA_LOCAL_DATACENTER:datacenter1}
    keyspace-name: ${CASSANDRA_KEYSPACE:sample_app}
    schema-action: none

cassandra:
  auto-migration:
    mode: ${CASSANDRA_MIGRATION_MODE:DRY_RUN}
